name: learn_rohd
description: Learning ROHD
version: 1.0.0
repository: https://github.com/ethanuppal/learn_rohd

environment:
  sdk: ^3.8.0

dependencies:
  rohd: ^0.6.3
  rohd_hcl: ^0.1.0

dependency_overrides:
  rohd: ^0.6.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
